34 connect with nbp api
IIS-ZPI/ZPI2023_IO1_GYM_BROS pull request #36
Opened 2024-04-11 11:02 UTC by Misiek22113

- added api calls for singular currency
- added api calls of currency mid value for specified period of time

closes #34

2024-04-11 11:05 UTC, olekgolus11 requested changes
Make it a hook

2024-04-11 15:01 UTC, Gujansko approved these changes

2024-04-12 08:44 UTC, BartoszChadrys approved these changes

2024-04-13 13:14 UTC, olekgolus11 approved these changes

2024-04-17 16:22 UTC, merged